controller_manager:
  ros__parameters:
    update_rate: 50
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - XL_430_base_Revolute-29
      - XL_430_shoulder_Revolute-30
      - XL_430_upper_Revolute-31
      - XL_430_lower_Revolute-32
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    gains:
      XL_430_base_Revolute-29:
        p: 5.0
        i: 0.0
        d: 1.0
      XL_430_shoulder_Revolute-30:
        p: 5.0
        i: 0.0
        d: 1.0
      XL_430_upper_Revolute-31:
        p: 5.0
        i: 0.0
        d: 1.0
      XL_430_lower_Revolute-32:
        p: 5.0
        i: 0.0
        d: 1.0
    constraints:
      goal_time: 0.3
      stopped_velocity_tolerance: 0.01
      XL_430_base_Revolute-29:
        goal: 0.5
      XL_430_shoulder_Revolute-30:
        goal: 0.5
      XL_430_upper_Revolute-31:
        goal: 0.5
      XL_430_lower_Revolute-32:
        goal: 0.5