controller_manager:
  ros__parameters:
    update_rate: 50
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - revolute_2
      - revolute_8
      - revolute_15
      - revolute_19
      - revolute_25
      - revolute_50
      - revolute_51
      - revolute_53
      - revolute_62
      - revolute_65
      - revolute_67
      - revolute_70
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    gains:
      revolute_2:
        p: 100.0
        d: 10.0
        i: 0.0
      revolute_8:
        p: 100.0
        d: 10.0
        i: 0.0
      revolute_15:
        p: 100.0
        d: 10.0
        i: 0.0
      revolute_19:
        p: 100.0
        d: 10.0
        i: 0.0
      revolute_25:
        p: 100.0
        d: 10.0
        i: 0.0
      revolute_50:
        p: 100.0
        d: 10.0
        i: 0.0
      revolute_51:
        p: 100.0
        d: 10.0
        i: 0.0
      revolute_53:
        p: 100.0
        d: 10.0
        i: 0.0
      revolute_62:
        p: 100.0
        d: 10.0
        i: 0.0
      revolute_65:
        p: 100.0
        d: 10.0
        i: 0.0
      revolute_67:
        p: 100.0
        d: 10.0
        i: 0.0
      revolute_70:
        p: 100.0
        d: 10.0
        i: 0.0
    constraints:
      goal_time: 0.3
      stopped_velocity_tolerance: 0.01
      revolute_2:
        goal: 0.01
      revolute_8:
        goal: 0.01
      revolute_15:
        goal: 0.01
      revolute_19:
        goal: 0.01
      revolute_25:
        goal: 0.01
      revolute_50:
        goal: 0.01
      revolute_51:
        goal: 0.01
      revolute_53:
        goal: 0.01
      revolute_62:
        goal: 0.01
      revolute_65:
        goal: 0.01
      revolute_67:
        goal: 0.01
      revolute_70:
        goal: 0.01
